version: '3.8'

services:
  express-server:
    image: lb2idocker/djra_project:latest
    ports:
      - "3000:3000"
    volumes:
      - /workspace:/app
    working_dir: /app
    command: npm start

  rest-assured-tests:
    image: lb2idocker/djra_project:latest
    depends_on:
      - express-server
    volumes:
      - /workspace:/app
    working_dir: /app
    command: mvn test
